import { useState } from "react";
import { Check, Mail, Sparkles } from "lucide-react";
import { useApp } from "../context/AppContext";

export default function Premium() {
  const { user } = useApp();
  const [email, setEmail] = useState(user?.email || "");
  const [sent, setSent] = useState(false);
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (email.includes("@")) setSent(true); };
  return <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20"><div className="text-center max-w-2xl mx-auto"><div className="w-14 h-14 rounded-2xl bg-gold-100 flex items-center justify-center mx-auto mb-5"><Sparkles className="w-7 h-7 text-gold-600" /></div><p className="text-xs uppercase tracking-[0.25em] text-gold-600">B&F 45 Premium</p><h1 className="font-serif text-4xl md:text-5xl text-bordeaux-950 mt-3">Il tuo sommelier personale.</h1><p className="text-bordeaux-600 mt-4 text-lg">Consulenze private, abbinamenti esclusivi e accesso anticipato alle nuove selezioni.</p></div><div className="max-w-md mx-auto mt-10 p-7 rounded-2xl bg-bordeaux-950 text-cream-100 text-center"><p className="text-sm text-cream-300">14 giorni gratis se ti iscrivi entro il 30 settembre</p><div className="mt-3"><strong className="font-serif text-5xl text-gold-400">€4,90</strong><span className="text-cream-300"> / mese</span></div><ul className="text-left space-y-3 mt-6">{["Consulenze AI private illimitate", "Abbinamenti esclusivi via email", "Storico preferenze e gusto", "Nuove selezioni in anteprima", "Nessun vincolo, cancelli quando vuoi"].map((item) => <li key={item} className="flex items-center gap-2 text-sm text-cream-200"><Check className="w-4 h-4 text-gold-400" />{item}</li>)}</ul>{sent ? <div className="mt-7 p-4 rounded-lg bg-bordeaux-800 text-sm text-gold-200">Controlla la tua email: ti abbiamo inviato il link per attivare i 14 giorni gratuiti.</div> : <form onSubmit={submit} className="mt-7"><div className="relative"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-bordeaux-400" /><input required type="email" placeholder="La tua email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full pl-9 pr-3 py-3 rounded-lg bg-cream-50 text-bordeaux-950 placeholder:text-bordeaux-400 focus:outline-none focus:ring-2 focus:ring-gold-400" /></div><button type="submit" className="w-full mt-3 py-3 rounded-lg bg-gold-400 text-bordeaux-950 font-semibold hover:bg-gold-300 transition-colors">Attiva prova gratuita</button></form>}</div><p className="text-center text-xs text-bordeaux-500 mt-6">Nessun pagamento oggi. Il piano sarà attivabile quando collegheremo il pagamento reale.</p></div>;
}
